import { TypographyOptions } from "@mui/material/styles/createTypography";

export const typography: TypographyOptions = {
  h1: {
    fontFamily: "CormorantInfant",
    fontSize: "80px",
    fontWeight: 400,
    lineHeight: 1.08,
    letterSpacing: "0",
    color: "#1a1a1a",
    textDecoration: "none",
  },
  h2: {
    fontFamily: "CormorantInfant",
    fontSize: "68.8px",
    fontWeight: 400,
    lineHeight: 1.08,
    letterSpacing: "0",
    color: "#1a1a1a",
    textDecoration: "none",
  },
  h3: {
    fontFamily: "CormorantInfant",
    fontSize: "48.8px",
    fontWeight: 400,
    lineHeight: 1.08,
    letterSpacing: "0",
    color: "#1a1a1a",
    textDecoration: "none",
  },
  h4: {
    fontFamily: "CormorantInfant",
    fontSize: "40px",
    fontWeight: 400,
    lineHeight: 1.08,
    letterSpacing: "0",
    color: "#1a1a1a",
    textDecoration: "none",
  },
  intro: {
    fontFamily: "CormorantInfant",
    fontSize: "40px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    color: "#1a1a1a",
    textDecoration: "none",
  },
  label: {
    fontFamily: "Raleway",
    fontSize: "16px",
    fontWeight: 500,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    color: "#1a1a1a",
    textTransform: "none",
    textAlign: "start",
    textDecoration: "none",
  },
  body: {
    fontFamily: "Raleway",
    fontSize: "16px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    color: "#1a1a1a",
    textTransform: "none",
    textAlign: "start",
    textDecoration: "none",
  },
  someSmall: {
    fontFamily: "Raleway",
    fontSize: "14px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    color: "#1a1a1a",
    textTransform: "none",
    textAlign: "start",
    textDecoration: "none",
  },
  small: {
    fontFamily: "Raleway",
    fontSize: "12.8px",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.04em",
    color: "#1a1a1a",
    textTransform: "none",
    textAlign: "start",
    textDecoration: "none",
  },
  // button: {
  //   fontSize: "20px",
  //   fontWeight: 500,
  //   lineHeight: 1.25,
  //   letterSpacing:"0.04em",
  // },
  fontFamily: ["CormorantInfant", "Raleway", "sans-serif"].join(","),
};
