import { BookingType } from "../../../../redux/slices/Bookings/types";

export const defaultFormValues: BookingType = {
  _id: "",
  room_id: "",
  room_category_id: "",
  user: {
    name: "",
    lastname: "",
    surname: "",
    phone: "",
    email: "",
    nationality: "",
    send_confirm_on_phone: false,
    want_to_know_about_special_offers_and_news: false,
  },
  adults_count: 0,
  children_count: 0,
  arrival_datetime: "",
  departure_datetime: "",
  tariff_id: "",
  service_id: [],
  bed_type_id: "",
  view_from_window_id: "",
  payment_method_id: "",
  transfer_id: "",
  transfer_comment: "",
  price: 0,
  comment: "",
  booking_for_whom: "for_yourself",
  created_at: "",
  updated_at: "",
};
